services:
  - type: web
    name: agrigrow-backend
    runtime: python
    rootDir: flask-backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DB_HOST
        sync: false        # Set manually in Render dashboard
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
